Repository Multi-KODI/KODI_project, pull requests merged in 2024-01, with the labels that each got.

#5 [ADD] SpringBootApplication
  KODI/pom.xml
  KODI/src/main/java/com/example/kodi/KodiApplication.java
  KODI/src/main/java/com/example/kodi/ServletInitializer.java
  KODI/src/main/java/controller/DiningCostController.java
  KODI/src/main/java/dao/DiningCostDAO.java
  KODI/src/main/java/dto/DiningCostDTO.java
  KODI/src/main/java/service/DiningCostService.java
  KODI/src/main/resources/mybatis/mapper/mybatis-mapping.xml
  KODI/src/main/resources/mybatis/mybatis-config.xml
  KODI/src/main/resources/static/css/DiningCost.css
  KODI/src/main/webapp/WEB-INF/views/DiningCost.jsp
Labels: bug

#17 [ADD],[UPDATE] 마이페이지 구현
  KODI/src/main/java/controller/MyPageController.java
  KODI/src/main/java/dao/MemberDAO.java
  KODI/src/main/java/dao/MyPageDAO.java
  KODI/src/main/java/service/MemberService.java
  KODI/src/main/java/service/MyPageService.java
Labels: documentation, enhancement

#20 [ADD], [UPDATE] 관리자 기능 구현
  KODI/src/main/java/controller/AdminController.java
  KODI/src/main/java/dao/AdminDAO.java
  KODI/src/main/java/dao/MemberDAO.java
  KODI/src/main/java/service/AdminService.java
  KODI/src/main/java/service/EmailService.java
  KODI/src/main/java/service/MemberService.java
  KODI/src/main/java/service/MyPageService.java
Labels: documentation, enhancement

#24 [ADD] 채팅 리스트 페이지 UI 구현
  KODI/src/main/java/controller/ChatListController.java
  KODI/src/main/java/dao/ChatListDAO.java
  KODI/src/main/java/dto/ChatListDTO.java
  KODI/src/main/java/dto/ChatListFriendDTO.java
  KODI/src/main/java/dto/ChatListRoomDTO.java
  KODI/src/main/java/service/ChatListService.java
  KODI/src/main/resources/mybatis/mapper/ChatList-mapping.xml
  KODI/src/main/resources/mybatis/mybatis-config.xml
  KODI/src/main/resources/static/css/ChatList.css
  KODI/src/main/resources/static/image/icon/live-chat.png
  KODI/src/main/webapp/WEB-INF/views/ChatList.jsp
Labels: documentation, enhancement

#29 [UPDATE] diningCost 및 ChatList 수정
  KODI/src/main/java/controller/ChatListController.java
  KODI/src/main/java/controller/DiningCostController.java
  KODI/src/main/java/controller/MyPageController.java
  KODI/src/main/java/dto/DiningCostDTO.java
  KODI/src/main/java/service/ChatListService.java
  KODI/src/main/resources/mybatis/mybatis-config.xml
  KODI/src/main/resources/static/css/Start.css
  KODI/src/main/webapp/WEB-INF/views/ChatList.jsp
  KODI/src/main/webapp/WEB-INF/views/Start.jsp
Labels: bug, documentation

#31 [FIX] .gitignore 수정
  KODI/.gitignore
Labels: bug

#39 [UPDATE] 채팅 리스트 페이지 CSS 수정
  KODI/src/main/webapp/WEB-INF/views/ChatList.jsp
Labels: documentation, enhancement

#41 [ADD] 실시간 채팅 페이지 초기 구현
  KODI/src/main/java/com/example/kodi/KodiApplication.java
  KODI/src/main/java/config/ResourceConfig.java
  KODI/src/main/java/config/WebSocketConfig.java
  KODI/src/main/java/config/WebSocketHandler.java
  KODI/src/main/java/controller/DiningCostController.java
  KODI/src/main/java/controller/LiveChatController.java
  KODI/src/main/java/dao/ChatListDAO.java
  KODI/src/main/java/dao/LiveChatDAO.java
  KODI/src/main/java/dto/AllChatDTO.java
  KODI/src/main/java/dto/ChatMsgRq.java
  KODI/src/main/java/service/ChatListService.java
  KODI/src/main/java/service/LiveChatService.java
  KODI/src/main/resources/mybatis/mapper/ChatList-mapping.xml
  KODI/src/main/resources/mybatis/mapper/LiveChat-mapping.xml
  KODI/src/main/resources/static/css/LiveChat.css
  KODI/src/main/resources/static/image/icon/exit-chat.png
  KODI/src/main/webapp/WEB-INF/views/Header.jsp
  KODI/src/main/webapp/WEB-INF/views/LiveChat.jsp
  KODI/src/main/webapp/WEB-INF/views/SearchHeader.jsp
Labels: documentation, enhancement

#47 [ADD] 채팅방 메시지 국적별 자동 번역
  KODI/src/main/java/config/NaverInfo.java
  KODI/src/main/java/config/WebSocketHandler.java
  KODI/src/main/java/controller/DiningCostController.java
  KODI/src/main/java/controller/LiveChatController.java
  KODI/src/main/java/dao/LiveChatDAO.java
  KODI/src/main/java/service/PapagoService.java
  KODI/src/main/resources/mybatis/mapper/LiveChat-mapping.xml
  KODI/src/main/webapp/WEB-INF/views/LiveChat.jsp
Labels: documentation, enhancement

#53 [UPDATE] Login 성공 시 경로 수정 및 HomeController 생성
  KODI/src/main/java/com/example/kodi/KodiApplication.java
  KODI/src/main/java/controller/HomeController.java
  KODI/src/main/webapp/WEB-INF/views/Home.jsp
  KODI/src/main/webapp/WEB-INF/views/Login.jsp
Labels: documentation, enhancement

#63 [UPDATE] 외식비 정보 제공 페이지, 게시글 상세 페이지 완성 및 채팅방 페이지 수정
  KODI/src/main/java/controller/ChatListController.java
  KODI/src/main/java/controller/DiningCostController.java
  KODI/src/main/java/controller/LiveChatController.java
  KODI/src/main/java/dao/ChatListDAO.java
  KODI/src/main/java/dao/LiveChatDAO.java
  KODI/src/main/java/service/ChatListService.java
  KODI/src/main/resources/mybatis/mapper/ChatList-mapping.xml
  KODI/src/main/resources/static/css/DiningCost.css
  KODI/src/main/webapp/WEB-INF/views/ChatList.jsp
  KODI/src/main/webapp/WEB-INF/views/DiningCost.jsp
  KODI/src/main/webapp/WEB-INF/views/LiveChat.jsp
  KODI/src/main/webapp/WEB-INF/views/ReadPostOne.jsp
Labels: bug, documentation, enhancement

#66 [UPDATE] 홈페이지 실시간 채팅방
  KODI/src/main/java/config/WebSocketConfig.java
  KODI/src/main/java/config/WebSocketHandler.java
  KODI/src/main/java/controller/ChatListController.java
  KODI/src/main/resources/static/css/Home.css
  KODI/src/main/webapp/WEB-INF/views/Home.jsp
Labels: documentation, enhancement

#71 [FIX] .gitignore 수정
  .gitignore
Labels: bug

#73 [UPDATE] 실시간 채팅 기능 & 게시글 상세 페이지 댓글 권한 수정
  KODI/src/main/java/config/WebSocketHandler.java
  KODI/src/main/java/controller/LiveChatController.java
  KODI/src/main/resources/static/css/ReadPostOne.css
  KODI/src/main/webapp/WEB-INF/views/Home.jsp
  KODI/src/main/webapp/WEB-INF/views/LiveChat.jsp
  KODI/src/main/webapp/WEB-INF/views/ReadPostOne.jsp
Labels: documentation, enhancement

#76 [ADD] 홈페이지 교통수단 비용 조회 API 추가
  KODI/src/main/java/controller/HomeController.java
  KODI/src/main/java/dao/HomeDAO.java
  KODI/src/main/java/dto/VehicleDTO.java
  KODI/src/main/java/service/HomeService.java
  KODI/src/main/resources/mybatis/mapper/Home-mapping.xml
  KODI/src/main/resources/mybatis/mybatis-config.xml
Labels: documentation, enhancement

#86 [UPDATE] 실시간 채팅 페이지 완성
  KODI/src/main/java/config/WebSocketConfig.java
  KODI/src/main/java/config/WebSocketHandler.java
  KODI/src/main/java/controller/LiveChatController.java
  KODI/src/main/webapp/WEB-INF/views/LiveChat.jsp
Labels: documentation, enhancement

#94 [UPDATE] 게시글 상세 페이지 좋아요 여부에 따라 아이콘 색상 변경
  KODI/src/main/java/controller/ReadPostOneController.java
  KODI/src/main/resources/static/image/icon/full-love.png
  KODI/src/main/webapp/WEB-INF/views/ReadPostOne.jsp
Labels: documentation, enhancement

#101 [UPDATE] 실시간 채팅 페이지, 홈페이지 수정
  KODI/src/main/java/controller/HomeController.java
  KODI/src/main/java/dao/HomeDAO.java
  KODI/src/main/java/dto/HomeAllChatDTO.java
  KODI/src/main/java/dto/HomeChatMsgDTO.java
  KODI/src/main/java/service/HomeService.java
  KODI/src/main/resources/mybatis/mapper/Home-mapping.xml
  KODI/src/main/resources/mybatis/mybatis-config.xml
  KODI/src/main/resources/static/css/Home.css
  KODI/src/main/resources/static/css/LiveChat.css
  KODI/src/main/webapp/WEB-INF/views/ChatList.jsp
  KODI/src/main/webapp/WEB-INF/views/Home.jsp
  KODI/src/main/webapp/WEB-INF/views/LiveChat.jsp
Labels: documentation, enhancement
