Repository Multi-KODI/KODI_project, pull requests merged in 2024-02, with the labels that each got.

#111 [UPDATE] session 없을 경우 처리
  KODI/src/main/java/controller/ChatListController.java
  KODI/src/main/java/controller/DiningCostController.java
  KODI/src/main/java/controller/HomeController.java
  KODI/src/main/java/controller/LiveChatController.java
  KODI/src/main/java/controller/ReadPostOneController.java
  KODI/src/main/java/controller/StartController.java
  KODI/src/main/webapp/WEB-INF/views/ChatList.jsp
  KODI/src/main/webapp/WEB-INF/views/DiningCost.jsp
  KODI/src/main/webapp/WEB-INF/views/Home.jsp
  KODI/src/main/webapp/WEB-INF/views/LiveChat.jsp
  KODI/src/main/webapp/WEB-INF/views/ReadPostOne.jsp
  KODI/src/main/webapp/WEB-INF/views/Start.jsp
Labels: bug, documentation

#115 [UPDATE] 게시글 상세 페이지 이미지 크기 수정 및 이미지 섹션 분리
  KODI/src/main/resources/static/css/ReadPostOne.css
  KODI/src/main/webapp/WEB-INF/views/ReadPostOne.jsp
Labels: documentation, enhancement

#117 [UPDATE]게시글 저장 오류 해결
  KODI/src/main/java/controller/ModifyPostController.java
  KODI/src/main/java/controller/WritePostController.java
  KODI/src/main/java/dao/ModifyPostDAO.java
  KODI/src/main/java/dto/WritePostDTO.java
  KODI/src/main/java/service/ModifyPostService.java
  KODI/src/main/java/service/WritePostService.java
  KODI/src/main/resources/mybatis/mapper/ModifyPost-mapping.xml
  KODI/src/main/webapp/WEB-INF/views/Editpost.jsp
Labels: bug

#119 [ADD]지도 페이지 jsp,script,back-end 마킹기능 완료
  KODI/src/main/java/controller/MapController.java
  KODI/src/main/java/dao/MapDAO.java
  KODI/src/main/java/service/MapService.java
  KODI/src/main/resources/mybatis/mapper/Map-mapping.xml
  KODI/src/main/webapp/WEB-INF/views/Map.jsp
Labels: documentation

#122 [UPDATE] 외식비 정보 제공 전체 카테고리 추가
  KODI/src/main/webapp/WEB-INF/views/DiningCost.jsp
Labels: documentation, enhancement

#124 [UPDATE]수정 페이지 - 이미지 삭제와 session 검증 추가
  KODI/src/main/java/controller/ModifyPostController.java
  KODI/src/main/java/dao/ModifyPostDAO.java
  KODI/src/main/java/service/ModifyPostService.java
  KODI/src/main/resources/mybatis/mapper/ModifyPost-mapping.xml
Labels: documentation, enhancement

#126 Develop2
  KODI/src/main/resources/static/css/Planner.css
  KODI/src/main/resources/static/css/ReadPostAll.css
  KODI/src/main/resources/static/css/WritePost.css
  KODI/src/main/resources/static/image/db/noImage.png
  KODI/src/main/resources/static/js/Planner.js
  KODI/src/main/webapp/WEB-INF/views/Editpost.jsp
  KODI/src/main/webapp/WEB-INF/views/Join.jsp
  KODI/src/main/webapp/WEB-INF/views/Planner.jsp
  KODI/src/main/webapp/WEB-INF/views/ReadPostAll.jsp
  KODI/src/main/webapp/WEB-INF/views/WritePost.jsp
Labels: enhancement

#129 [UPDATE]각각의 컨트롤러에 세션 유지 여부 확인 코드 추가
  KODI/src/main/java/controller/MapController.java
  KODI/src/main/java/controller/ReadPostAllController.java
  KODI/src/main/java/controller/SearchListController.java
  KODI/src/main/java/controller/WritePostController.java
Labels: documentation, enhancement

#133 [UPDATE]검색 결과 리스트 오류 수정
  KODI/src/main/java/controller/SearchListController.java
  KODI/src/main/java/dao/SearchMemberListDAO.java
  KODI/src/main/java/service/SearchMemberListService.java
  KODI/src/main/resources/mybatis/mapper/SearchMemberList-mapping.xml
  KODI/src/main/webapp/WEB-INF/views/SearchList/SearchListMember.jsp
Labels: bug, enhancement

#137 Develop2
  KODI/src/main/resources/static/css/ReadPostAll.css
  KODI/src/main/resources/static/css/WritePost.css
  KODI/src/main/resources/static/js/Planner.js
  KODI/src/main/webapp/WEB-INF/views/Editpost.jsp
  KODI/src/main/webapp/WEB-INF/views/Planner.jsp
  KODI/src/main/webapp/WEB-INF/views/WritePost.jsp
Labels: bug, documentation, enhancement

#142 [UPDATE]지도페이지 검색기능 수정 & 마킹 삭제시 확인 절차 추가
  KODI/src/main/webapp/WEB-INF/views/Map.jsp
Labels: bug, enhancement

#144 회원가입 페이지 수정
  KODI/src/main/webapp/WEB-INF/views/Join.jsp
Labels: bug, enhancement

#145 [UPDATE]검색 결과 리스트 - 태그 조회시 중복 제거
  KODI/src/main/resources/mybatis/mapper/SearchPostList-mapping.xml
Labels: bug, enhancement

#153 [UPDATE]지도페이지, SearchHeader, 여행 일정페이지, 게시글 작성 페이지 언어 선택 기능 추가
  KODI/src/main/webapp/WEB-INF/views/Map.jsp
  KODI/src/main/webapp/WEB-INF/views/Planner.jsp
  KODI/src/main/webapp/WEB-INF/views/SearchHeader.jsp
  KODI/src/main/webapp/WEB-INF/views/WritePost.jsp
Labels: documentation, enhancement

#162 Develop2
  KODI/src/main/webapp/WEB-INF/views/Editpost.jsp
Labels: bug

#161 [UPDATE]게시글 작성&수정 페이지 이미지 이름 겹치는 경우 덮어쓰기 오류 해결
  KODI/src/main/java/controller/ModifyPostController.java
  KODI/src/main/java/controller/WritePostController.java
Labels: bug, enhancement

#165 [UPDATE] 게시글 수정 페이지, 모든게시글 페이지 언어 설정 추가
  KODI/src/main/resources/static/css/ReadPostAll.css
  KODI/src/main/webapp/WEB-INF/views/Editpost.jsp
  KODI/src/main/webapp/WEB-INF/views/ReadPostAll.jsp
  KODI/src/main/webapp/WEB-INF/views/WritePost.jsp
Labels: enhancement

#221 [UPDATE]필수입력 기능 오류 수정
  KODI/src/main/webapp/WEB-INF/views/Join.jsp
Labels: bug
